import { Mnemonic as MnemonicReport } from "../../../locators/reports";

export const mnemonicReport = {

    // Texts
    reportsCustomerTitle: () => cy.get(MnemonicReport.reportsCustomerTitle),
    reportTypeLabel: () => cy.get(MnemonicReport.reportTypeText),
    enrollmentDateLabel: () => cy.get(MnemonicReport.enrollmentDateText),
    enrollmentDateFromLabel: () => cy.get(MnemonicReport.enrollmentDateFromText),
    enrollmentDateToLabel: () => cy.get(MnemonicReport.enrollmentDateToText),
    activationDateLabel: () => cy.get(MnemonicReport.activationDateText),
    activationDateFromLabel: () => cy.get(MnemonicReport.activationDateFromText),
    activationDateToLabel: () => cy.get(MnemonicReport.activationDateToText),
    clientTypeLabel: () => cy.get(MnemonicReport.clientTypeText),
    clientRetailTypeLabel: () => cy.get(MnemonicReport.clientRetailTypeText),
    clientNameLabel: () => cy.get(MnemonicReport.clientNameText),
    mnemonicLabel: () => cy.get(MnemonicReport.mnemonicText),
    mnemonicStatusLabel: () => cy.get(MnemonicReport.mnemonicStatusText),
    generateReportLabel: () => cy.get(MnemonicReport.generateReportText),
    transactionTypeLabel: () => cy.get(MnemonicReport.transactionTypeText),
    valueDateLabel: () => cy.get(MnemonicReport.valueDateText),
    valueDateFromLabel: () => cy.get(MnemonicReport.valueDateFromText),
    valueDateToLabel: () => cy.get(MnemonicReport.valueDateToText),
    mobileNoLabel: () => cy.get(MnemonicReport.mobileNoText),
    statusLabel: () => cy.get(MnemonicReport.statusText),
    emailAddLabel: () => cy.get(MnemonicReport.emailAddText),
    dateUploadedLabel: () => cy.get(MnemonicReport.dateUploadedText),
    dateUploadedFromLabel: () => cy.get(MnemonicReport.dateUploadedText),
    dateUploadedToLabel: () => cy.get(MnemonicReport.dateUploadedToText),
    dateActivatedLabel: () => cy.get(MnemonicReport.dateActivatedText),
    dateActivatedFromLabel: () => cy.get(MnemonicReport.dateActivatedFromText),
    dateActivatedToLabel: () => cy.get(MnemonicReport.dateActivatedToText),

    // Buttons
    generateReportButton: () => cy.get(MnemonicReport.generateReportButton),

    // Input Box
    clientNameInput: () => cy.get(MnemonicReport.clientNameInput),
    mnemonicInput: () => cy.get(MnemonicReport.mnemonicInput),
    mobileNoInput: () => cy.get(MnemonicReport.mobileNoInput),
    emailAddInput: () => cy.get(MnemonicReport.emailAddInput),

    // Calendar
    enrollmentDateFromCalendar: () => cy.get(MnemonicReport.enrollmentDateFromCalendar),
    enrollmentDateToCalendar: () => cy.get(MnemonicReport.enrollmentDateToCalendar),
    activationDateFromCalendar: () => cy.get(MnemonicReport.activationDateFromCalendar),
    activationDateToCalendar: () => cy.get(MnemonicReport.activationDateToCalendar),
    valueDateFromCalendar: () => cy.get(MnemonicReport.valueDateFromCalendar),
    valueDateToCalendar: () => cy.get(MnemonicReport.valueDateToCalendar),
    dateUploadedFromCalendar: () => cy.get(MnemonicReport.dateUploadedFromCalendar),
    dateUploadedToCalendar: () => cy.get(MnemonicReport.dateUploadedToCalendar),
    dateActivatedFromCalendar: () => cy.get(MnemonicReport.dateActivatedFromCalendar),
    dateActivatedToCalendar: () => cy.get(MnemonicReport.dateActivatedToCalendar),

    // Dropdown
    reportTypeDropdown: () => cy.get(MnemonicReport.reportTypeDropdown),
    listOfEnrolledMnemonicDropdown: () => cy.get(MnemonicReport.listOfEnrolledMnemonicDropdown),
    clientTypeDropdown: () => cy.get(MnemonicReport.clientTypeDropdown),
    clientRetailTypeDropdown: () => cy.get(MnemonicReport.clientRetailTypeDropdown),
    mnemonicStatusDropdown: () => cy.get(MnemonicReport.mnemonicStatusDropdown),
    listOfEnrolledMnemonicWithTransactionDropdown: () => cy.get(MnemonicReport.listOfEnrolledMnemonicDropdown),
    transactionTypeDropdown: () => cy.get(MnemonicReport.transactionTypeDropdown),
    listOfMnemonicWithUpdatesDropdown: () => cy.get(MnemonicReport.listOfMnemonicsWithUpdatesDropdown),
    extractableReportBasedValueOnSearchFilterDropdown: () => cy.get(MnemonicReport.extractableReportBasedValueOnSearchFilterDropdown),
    statusDropdown: () => cy.get(MnemonicReport.statusDropdown),

    // Options
    listOfEnrolledMnemonicOption: () => cy.get(MnemonicReport.listOfEnrolledMnemonicOption),
    listofMnemonicsWithUpdatesOption: () => cy.get(MnemonicReport.listOfMnemonicsWithUpdatesOption),
    extractableReportBasedValueOnSearchFilterOption: () => cy.get(MnemonicReport.extractableReportBasedValueOnSearchFilterOption),
    consolidatedCustomerReportOption: () => cy.get(MnemonicReport.consolidatedCustomerReportOption),
    retailOption: () => cy.get(MnemonicReport.retailOption),
    corporateOption: () => cy.get(MnemonicReport.corporateOption),
    individualOption: () => cy.get(MnemonicReport.individualOption),
    jointOption: () => cy.get(MnemonicReport.jointOption),
    productOption: () => cy.get(MnemonicReport.productOption),
    documentOption: () => cy.get(MnemonicReport.documentOption),
    pendingApprovalOption: () => cy.get(MnemonicReport.pendingApprovalOption),
    forProcessingOption: () => cy.get(MnemonicReport.forProcessingOption),
    cancelledOption: () => cy.get(MnemonicReport.cancelledOption),
    postDealRejectedOption: () => cy.get(MnemonicReport.postDealRejectedOption),
    postDealForAcceptanceOption: () => cy.get(MnemonicReport.postDealForAcceptanceOption),
    postDealForAcknowledgementOption: () => cy.get(MnemonicReport.postDealForAcknowledgementOption),
    completedWithConfoOption: () => cy.get(MnemonicReport.completedWithConfoOption),
    completedOption: () => cy.get(MnemonicReport.completedOption),
    consolidatedCustomerReportDropdown: () => cy.get(MnemonicReport.consolidatedCustomerReportDropdown),
    dateUploadedToOption: () => cy.get(MnemonicReport.dateUploadedToOption),

    //+--------------------------------------------------------------------+
    //|                                                                    |
    //|                       ACTION METHODS                               |
    //|                                                                    |
    //+--------------------------------------------------------------------+

    clickGenerateReportButton: () => cy.get(MnemonicReport.generateReportButton).click(),

    typeClientNameInput: (input: string) => cy.get(MnemonicReport.clientNameInput).type(input),
    typeMnemonicInput: (input: string) => cy.get(MnemonicReport.mnemonicInput).type(input),
    typeMobileNoInput: (input: string) => cy.get(MnemonicReport.mobileNoInput).type(input),
    typeEmailAddInput: (input: string) => cy.get(MnemonicReport.emailAddInput).type(input),

    clickEnrollmentDateFromCalendar: () => cy.get(MnemonicReport.enrollmentDateFromCalendar).click(),
    clickEnrollmentDateToCalendar: () => cy.get(MnemonicReport.enrollmentDateToCalendar).click(),
    clickActivationDateFromCalendar: () => cy.get(MnemonicReport.activationDateFromCalendar).click(),
    clickActivationDateToCalendar: () => cy.get(MnemonicReport.activationDateToCalendar).click(),
    clickValueDateFromCalendar: () => cy.get(MnemonicReport.valueDateFromCalendar).click(),
    clickValueDateToCalendar: () => cy.get(MnemonicReport.valueDateToCalendar).click(),
    clickDateUploadedFromCalendar: () => cy.get(MnemonicReport.dateUploadedFromCalendar).click(),
    clickDateUploadedToCalendar: () => cy.get(MnemonicReport.dateUploadedToCalendar).click(),
    clickDateActivatedFromCalendar: () => cy.get(MnemonicReport.dateActivatedFromCalendar).click(),
    clickDateActivatedToCalendar: () => cy.get(MnemonicReport.dateActivatedToCalendar).click(),

    clickReportTypeDropdown: () => cy.get(MnemonicReport.reportTypeDropdown).click(),
    clickListOfEnrolledMnemonicDropdown: () => cy.get(MnemonicReport.listOfEnrolledMnemonicDropdown).click(),
    clickClientTypeDropdown: () => cy.get(MnemonicReport.clientTypeDropdown).click(),
    clickClientRetailTypeDropdown: () => cy.get(MnemonicReport.clientRetailTypeDropdown).click(),
    clickMnemonicStatusDropdown: () => cy.get(MnemonicReport.mnemonicStatusDropdown).click(),
    clickListOfEnrolledMnemonicWithTransactionDropdown: () => cy.get(MnemonicReport.listOfEnrolledMnemonicDropdown).click(),
    clickTransactionTypeDropdown: () => cy.get(MnemonicReport.transactionTypeDropdown).click(),
    clickListOfMnemonicWithUpdatesDropdown: () => cy.get(MnemonicReport.listOfMnemonicsWithUpdatesDropdown).click(),
    clickExtractableReportBasedValueOnSearchFilterDropdown: () => cy.get(MnemonicReport.extractableReportBasedValueOnSearchFilterDropdown).click(),
    clickStatusDropdown: () => cy.get(MnemonicReport.statusDropdown).click(),

    clickListOfEnrolledMnemonicOption: () => cy.get(MnemonicReport.listOfEnrolledMnemonicOption).click(),
    clickListofMnemonicsWithUpdatesOption: () => cy.get(MnemonicReport.listOfMnemonicsWithUpdatesOption).click(),
    clickExtractableReportBasedValueOnSearchFilterOption: () => cy.get(MnemonicReport.extractableReportBasedValueOnSearchFilterOption).click(),
    clickConsolidatedCustomerReportOption: () => cy.get(MnemonicReport.consolidatedCustomerReportOption).click(),
    clickRetailOption: () => cy.get(MnemonicReport.retailOption).click(),
    clickCorporateOption: () => cy.get(MnemonicReport.corporateOption).click(),
    clickIndividualOption: () => cy.get(MnemonicReport.individualOption).click(),
    clickJointOption: () => cy.get(MnemonicReport.jointOption).click(),
    clickProductOption: () => cy.get(MnemonicReport.productOption).click(),
    clickDocumentOption: () => cy.get(MnemonicReport.documentOption).click(),
    clickPendingApprovalOption: () => cy.get(MnemonicReport.pendingApprovalOption).click(),
    clickForProcessingOption: () => cy.get(MnemonicReport.forProcessingOption).click(),
    clickCancelledOption: () => cy.get(MnemonicReport.cancelledOption).click(),
    clickPostDealRejectedOption: () => cy.get(MnemonicReport.postDealRejectedOption).click(),
    clickPostDealForAcceptanceOption: () => cy.get(MnemonicReport.postDealForAcceptanceOption).click(),
    clickPostDealForAcknowledgementOption: () => cy.get(MnemonicReport.postDealForAcknowledgementOption).click(),
    clickCompletedWithConfoOption: () => cy.get(MnemonicReport.completedWithConfoOption).click(),
    clickCompletedOption: () => cy.get(MnemonicReport.completedOption).click(),
    clickConsolidatedCustomerReportDropdown: () => cy.get(MnemonicReport.consolidatedCustomerReportDropdown).click(),
    clickDateUploadedToOption: () => cy.get(MnemonicReport.dateUploadedToOption).click(),
}