export const MViewRequest = {
  viewRequestCorporateTitle: "[data-test-id='header-view-request-corporate-label']",
  viewRequestRetailTitle: "[data-test-id='header-view-request-retail-label']",
  authorizeButton: "[data-test-id='sidebar-authorize-button']",
  returnToMakerButton: "[data-test-id='sidebar-return-to-maker-button']",
  cancelRequestButton: "[data-test-id='sidebar-cancel-request-button']",
  completeRequestButton: "[data-test-id='sidebar-complete-request-button']",
  requestHistoryButton: "[data-test-id='sidebar-request-history-button']",
  identifierTableHeader: "[data-test-id='main-page-identifier-header']",
  requestTableHeader: "[data-test-id='main-page-request-header']",
  rowCountTableHeader: "[data-test-id='main-page--header']",
  mnemonicTableHeader: "[data-test-id='main-page-mnemonic-header']",
  approverNameTableHeader: "[data-test-id='main-page-approver-name-header']",
  mobileNumberTableHeader: "[data-test-id='main-page-mobile-number-header']",
  emailAddressTableHeader: "[data-test-id='main-page-email-address-header']",
  clientNameTableHeader: "[data-test-id='main-page-client-name-header']",
  categoryTableHeader: "[data-test-id='main-page-category-header']",
  servicingUnitTableHeader: "[data-test-id='main-page-servicing-unit-header']",
  validationRemarksTableHeader: "[data-test-id='main-page-validation-remarks-header']",
  checkerRemarksTableHeader: "[data-test-id='main-page-checker-remarks-header']",
  statusTableHeader: "[data-test-id='main-page-status-header']",
  rowCountTableData: "[data-test-id='main-page-row-count-data-']",
  requestTableData: "[data-test-id='main-page-request-data-']",
  mnemonicTableData: "[data-test-id='main-page-mnemomic-data-']",
  approverNameTableData: "[data-test-id='main-page-approver-name-data-']",
  mobileNumberTableData: "[data-test-id='main-page-mobile-number-data-']",
  emailAddressTableData: "[data-test-id='main-page-email-address-data-']",
  clientNameTableData: "[data-test-id='main-page-client-name-data-']",
  categoryTableData: "[data-test-id='main-page-category-data-']",
  servicingUnitTableData: "[data-test-id='main-page-servicing-unit-data-']",
  validationRemarksTableData: "[data-test-id='main-page-validation-remarks-data-']",
  checkerRemarksTableData: "[data-test-id='main-page-checker-remarks-data-']",
  statusTableData: "[data-test-id='main-page-status-data-']",
  requestIdInput: "[data-test-id='main-page-request-id-text']",
  statusInput: "[data-test-id='main-page-status-text']",

  identifierTableData: "[data-test-id='main-page-identifier-data-']",
  cancelRequestLabel: "[data-test-id='sidebar-cancel-request-label']",
  completeRequestLabel: "[data-test-id='sidebar-complete-request-label']",
  requestHistoryLabel: "[data-test-id='sidebar-request-history-label']",
  statusLabel: "[data-test-id='main-page-status-label']",

  authorizeLabel: "[data-test-id='sidebar-authorize-label']",
  returnToMakerLabel: "[data-test-id='sidebar-return-to-maker-label']",
}

export const MMViewRequest = {
  submitButton: "[data-test-id='sidebar-submit-button']",
  submitButtonLabel: "[data-test-id='sidebar-submit-label']",
  requestIdLabel: "[data-test-id='main-page-request-id-label']",
  lastUpdateDateLabel: "[data-test-id='main-page-last-update-date-label']",
  lastUpdateDateInput: "[data-test-id='main-page-last-update-date-text']",
  configureAuthorizationTableHeader: "[data-test-id='main-page-ca-header']",
  configureAuthorizationTableData: "[data-test-id='main-page-ca-data-']",


  requestHistoryTable: "[data-test-id='main-page-request-history-table']",
  requestHistoryTableHeader: "[data-test-id='main-page-request-history-header']",
  requestHistoryTableRow: "[data-test-id='main-page-request-history-row-']",
  paginationCountLabel: "[data-test-id='main-page-pagination-count-label']",
}

export const MCViewRequest = {
  requestTableHeader: "[data-test-id='main-page-table-header']",

  lastUpdateDateLabel: "[data-test-id='main-page-last-update-label']",
  lastUpdateDateInput: "[data-test-id='main-page-last-update-text']",
}

export const viewRequestHistory = {
  requestHistoryTitle: "[data-test-id='header-request-history-label']",
  requestTableRow: "[data-test-id='main-page-table-row-']",
  requestHistoryForClientTitle: "[data-test-id='main-page-request-history-for-client-label']",
  userIdTableHeader: "[data-test-id='main-page-user-id-header']",
  nameTableHeader: "[data-test-id='main-page-name-header']",
  requestIdTableHeader: "[data-test-id='main-page-request-id-header']",
  retailClientTypeTableHeader: "[data-test-id='main-page-retail-client-type-header']",
  actionTableHeader: "[data-test-id='main-page-action-header']",
  requestStatusTableHeader: "[data-test-id='main-page-request-status-header']",
  mnemonicStatusTableHeader: "[data-test-id='main-page-mnemonic-status-header']",
  dateLoggedTableHeader: "[data-test-id='main-page-date-logged-header']",
  userIdTableData: "[data-test-id='main-page-user-id-data-']",
  nameTableData: "[data-test-id='main-page-name-data-']",
  requestIdTableData: "[data-test-id='main-page-request-id-data-']",
  retailClientTypeTableData: "[data-test-id='main-page-retail-client-type-data-']",
  actionTableData: "[data-test-id='main-page-action-data-']",
  requestStatusTableData: "[data-test-id='main-page-request-status-data-']",
  mnemonicStatusTableData: "[data-test-id='main-page-mnemonic-status-data-']",
  dateLoggedTableData: "[data-test-id='main-page-date-logged-data-']",
  previousPageButton: "[data-test-id='main-page-previous-page-button']",
  nextPageButton: "[data-test-id='main-page-next-page-button']",
}