export const ViewMnemonic = {
  viewMnemonicRetailTitle: "[data-test-id='header-view-mnemonic-retail-label']",
  configureAuthorizationText: "[data-test-id='sidebar-configure-authorization-label']",
  configureAuthorizationButton: "[data-test-id='sidebar-configure-authorization-button']",
  configureAuthorizationImage: "[data-test-id='sidebar-configure-authorization-svg']",
  mnemonicHistoryText: "[data-test-id='sidebar-mnemonic-history-label']",
  mnemonicHistoryButton: "[data-test-id='sidebar-mnemonic-history-button']",
  mnemonicHistoryImage: "[data-test-id='sidebar-mnemonic-history-svg']",
  tableHeader: "[data-test-id='main-page-table-header']",
  approverNameTableHeader: "[data-test-id='main-page-approver-name-header']",
  statusTableHeader: "[data-test-id='main-page-status-header']",
  mobileNumberTableHeader: "[data-test-id='main-page-mobile-number-header']",
  emailAddressTableHeader: "[data-test-id='main-page-email-address-header']",
  categoryTableHeader: "[data-test-id='main-page-category-header']",
  lastDateModifiedTableHeader: "[data-test-id='main-page-last-date-modified-header']", 
  tableRow: "[data-test-id='main-page-table-row-",
  approverNameTableData: "[data-test-id='main-page-approver-name-data-",
  statusTableData: "[data-test-id='main-page-status-data-']",
  mobileNumberTableData: "[data-test-id='main-page-mobile-number-data-",
  emailAddressTableData: "[data-test-id='main-page-email-address-data-",
  categoryTableData: "[data-test-id='main-page-category-data-",
  lastDateModifiedTableData: "[data-test-id='main-page-last-date-modified-data-",
  authorizedDealerTableHeader: "[data-test-id='main-page-authorized-dealer-name-header']",
  authorizedDealerTableData: "[data-test-id='main-page-authorized-dealer-data-",
  statusText: "[data-test-id='main-page-status-label']",
  statusInput: "[data-test-id='main-page-status-text']",
  lastUpdateDateText: "[data-test-id='main-page-last-update-date-label']",
  lastUpdateDateInput: "[data-test-id='main-page-last-update-date-text']",
  clientTitle: "[data-test-id='main-page-client-label']",
  mnemonicTitle: "[data-test-id='main-page-mnemonic-label']",
}

export const configureAuthorizationModal = {
  configureAuthorizationTitle: "[data-test-id='modal-configure-authorization-label']",
  approverSetupTitle: "[data-test-id='modal-approver-set-up-label']",
  modalTableHeader: "[data-test-id='modal-table-header']",
  modalTableRow: "[data-test-id='modal-table-row-']",
  modalCloseButton: "[data-test-id='modal-close-button']",
  modalCloseText: "[data-test-id='modal-close-label']",
}

export const ViewMnemonicMaker = {
  submitButton: "[data-test-id='sidebar-submit-button']",
  submitText: "[data-test-id='sidebar-submit-label']",
  requestTableData: "[data-test-id='main-page-request-data-",
  clientNameTable: "[data-test-id='main-page-client-name-data-",
  validationRemarksTable: "[data-test-id='main-page-validation-remarks-data-",
  checkerRemarksTable: "[data-test-id='main-page-checker-remarks-data-",
  requestIdText: "[data-test-id='main-page-request-id-label']",
  paginationCountText: "[data-test-id='main-page-pagination-count-label']",
}
export const ViewMnemonicChecker = {
  servicingUnitText: "[data-test-id='main-page-servicing-unit-label']",
  servicingUnitInput: "[data-test-id='main-page-servicing-unit-text']",
  authorizeButton: "[data-test-id='sidebar-authorize-button']",
  authorizeLabel: "[data-test-id='sidebar-authorize-label']",
  returnToMakerButton: "[data-test-id='sidebar-return-to-maker-button']",
  returnToMakerLabel: "[data-test-id='sidebar-return-to-maker-label']",
  cancelRequestButton: "[data-test-id='sidebar-cancel-request-button']",
  cancelRequestLabel: "[data-test-id='sidebar-cancel-request-label']",
  requestIdLabel: "[data-test-id='main-page-request-id-label']",
  requestHistoryLabel: "[data-test-id='sidebar-request-history-label']",
}

export const ViewMnemonicHistory = {
  mnemonicHistoryTitle: "[data-test-id='header-mnemonic-history-label']",
  mnemonicHistoryClientTitle: "[data-test-id='main-page-mnemonic-history-client-label']",
  mnemonicNameTitle: "[data-test-id='main-page-mnemonic-name-label']",
  userIdTableHeader: "[data-test-id='main-page-user-id-header']",
  mnemonicTableHeader: "[data-test-id='main-page-mnemonic-header']",
  nameTableHeader: "[data-test-id='main-page-name-data-header']",
  actionTableHeader: "[data-test-id='main-page-action-header']",
  statusTableHeader: "[data-test-id='main-page-status-header']",
  dateLoggedTableHeader: "[data-test-id='main-page-date-logged-header']",
  userIdTableData: "[data-test-id='main-page-user-id-data-",
  mnemonicTableData: "[data-test-id='main-page-mnemonic-data-",
  nameTableData: "[data-test-id='main-page-name-data-",
  actionTableData: "[data-test-id='main-page-action-data-",
  statusTableData: "[data-test-id='main-page-status-data-']",
  dateLoggedTableData: "[data-test-id='main-page-date-logged-data-",
  rowsPerPageText: "[data-test-id='main-page-rows-per-page-label']",
  rowsPerPageButton: "[data-test-id='main-page-rows-per-page-button']",
  previousPageButton: "[data-test-id='main-page-previous-page-button']",
  nextPageButton: "[data-test-id='main-page-next-page-button']",
}