import { CustomerMaintenance } from '../../../locators/customerMaintenance'

export const CustomerMaintenancePage = {
  customerMaintenanceTitle: () => cy.get(CustomerMaintenance.customerMaintenanceTitle),
  customerMaintenanceRetailTitle: () => cy.get(CustomerMaintenance.customerMaintenanceRetailTitle),
  customerMaintenanceCorporateTitle: () => cy.get(CustomerMaintenance.customerMaintenanceCorporateTitle),
  configureAuthorizationRetailTitle: () => cy.get(CustomerMaintenance.configureAuthorizationRetailTitle),
  configureAuthorizationCorporateTitle: () => cy.get(CustomerMaintenance.configureAuthorizationCorporateTitle),
  newRequestImage: () => cy.get(CustomerMaintenance.newRequestImage),
  retailImage: () => cy.get(CustomerMaintenance.retailImage),
  corporateImage: () => cy.get(CustomerMaintenance.corporateImage),
  viewRequestImage: () => cy.get(CustomerMaintenance.viewRequestImage),
  newRequestText: () => cy.get(CustomerMaintenance.newRequestText),
  retailText: () => cy.get(CustomerMaintenance.retailText),
  corporateText: () => cy.get(CustomerMaintenance.corporateText),
  viewRequestText: () => cy.get(CustomerMaintenance.viewRequestText),
  filterText: () => cy.get(CustomerMaintenance.filterText),
  searchText: () => cy.get(CustomerMaintenance.searchText),
  clientTypeText: () => cy.get(CustomerMaintenance.clientTypeText),
  extractText: () => cy.get(CustomerMaintenance.extractText),
  rowsPerPageText: () => cy.get(CustomerMaintenance.rowsPerPageText),
  paginationCountText: () => cy.get(CustomerMaintenance.paginationCountText),
  browseText: () => cy.get(CustomerMaintenance.browseText),
  uploadText: () => cy.get(CustomerMaintenance.uploadText),
  configureAuthorizationText: () => cy.get(CustomerMaintenance.configureAuthorizationText),
  enterMnemonicText: () => cy.get(CustomerMaintenance.enterMnemonicText),
  newRequestButton: () => cy.get(CustomerMaintenance.newRequestButton),
  retailButton: () => cy.get(CustomerMaintenance.retailButton),
  corporateButton: () => cy.get(CustomerMaintenance.corporateButton),
  viewRequestButton: () => cy.get(CustomerMaintenance.viewRequestButton),
  filterButton: () => cy.get(CustomerMaintenance.filterButton),
  searchButton: () => cy.get(CustomerMaintenance.searchButton),
  clientTypeButton: () => cy.get(CustomerMaintenance.clientTypeButton),
  extractButton: () => cy.get(CustomerMaintenance.extractButton),
  rowsPerPageButton: () => cy.get(CustomerMaintenance.rowsPerPageButton),
  previousPageButton: () => cy.get(CustomerMaintenance.previousPageButton),
  nextPageButton: () => cy.get(CustomerMaintenance.nextPageButton),
  configureAuthorizationButton: () => cy.get(CustomerMaintenance.configureAuthorizationButton),
  browseButton: () => cy.get(CustomerMaintenance.browseButton),
  uploadButton: () => cy.get(CustomerMaintenance.uploadButton),
  createRequestButton: () => cy.get(CustomerMaintenance.createRequestButton),
  searchInput: () => cy.get(CustomerMaintenance.searchInput),
  fileInput: () => cy.get(CustomerMaintenance.fileInput),
  customerMaintenanceTableHeader: () => cy.get(CustomerMaintenance.customerMaintenanceTableHeader),
  requestIdTableHeader: () => cy.get(CustomerMaintenance.requestIdTableHeader),
  requestTypeTableHeader: () => cy.get(CustomerMaintenance.requestTypeTableHeader),
  statusTableHeader: () => cy.get(CustomerMaintenance.statusTableHeader),
  requestDateTableHeader: () => cy.get(CustomerMaintenance.requestDateTableHeader),
  requestedByTableHeader: () => cy.get(CustomerMaintenance.requestedByTableHeader),
  clientTypeTableHeader: () => cy.get(CustomerMaintenance.clientTypeTableHeader),
  customerMaintenanceTable: () => cy.get(CustomerMaintenance.customerMaintenanceTable),
  customerMaintenanceTableRow: (id: number) => cy.get(`${CustomerMaintenance.customerMaintenanceTableRow}${id}`),
  requestIdTableData: (id: number) => cy.get(`${CustomerMaintenance.requestIdTableData}${id}`),
  requestTypeTableData: (id: number) => cy.get(`${CustomerMaintenance.requestTypeTableData}${id}`),
  statusTableData: (id: number) => cy.get(`${CustomerMaintenance.statusTableData}${id}`),
  requestDateTableData: (id: number) => cy.get(`${CustomerMaintenance.requestDateTableData}${id}`),
  requestedByTableData: (id: number) => cy.get(`${CustomerMaintenance.requestedByTableData}${id}`),
  clientTypeTableData: (id: number) => cy.get(`${CustomerMaintenance.clientTypeTableData}${id}`),

  //+--------------------------------------------------------------------+
  //|                                                                    |
  //|                       ACTION METHODS                               |
  //|                                                                    |
  //+--------------------------------------------------------------------+

  clickNewRequestButton: () => cy.get(CustomerMaintenance.newRequestButton).click,
  clickRetailButton: () => cy.get(CustomerMaintenance.retailButton).click,
  clickCorporateButton: () => cy.get(CustomerMaintenance.corporateButton).click,
  clickViewRequestButton: () => cy.get(CustomerMaintenance.viewRequestButton).click,
  clickFilterButton: () => cy.get(CustomerMaintenance.filterButton).click,
  clickSearchButton: () => cy.get(CustomerMaintenance.searchButton).click,
  clickClientTypeButton: () => cy.get(CustomerMaintenance.clientTypeButton).click,
  clickExtractButton: () => cy.get(CustomerMaintenance.extractButton).click,
  clickRowsPerPageButton: () => cy.get(CustomerMaintenance.rowsPerPageButton).click,
  clickPreviousPageButton: () => cy.get(CustomerMaintenance.previousPageButton).click,
  clickNextPageButton: () => cy.get(CustomerMaintenance.nextPageButton).click,
  clickVonfigureAuthorizationButton: () => cy.get(CustomerMaintenance.configureAuthorizationButton).click,
  clickBrowseButton: () => cy.get(CustomerMaintenance.browseButton).click,
  clickUploadButton: () => cy.get(CustomerMaintenance.uploadButton).click,
  clickCreateRequestButton: () => cy.get(CustomerMaintenance.createRequestButton).click,
}
