import { NewTransaction } from '../../../locators/newTransaction'

export const NewTransactionModulePage = {
  // Texts
  marketSalesTitle: () => cy.get(NewTransaction.marketSalesTitle),
  retailAccountsLabel: () => cy.get(NewTransaction.retailAccountsText),
  corporateAccountLabel: () => cy.get(NewTransaction.corporateAccountsText),
  moseRefNoText: () => cy.get(NewTransaction.moseRefNoText),
  selectTypeLabel: () => cy.get(NewTransaction.selectTypeText),
  documentRadioLabel: () => cy.get(NewTransaction.documentText),
  selectProductTypeLabel: () => cy.get(NewTransaction.selectProductTypeText),
  valueDateLabel: () => cy.get(NewTransaction.valueDateText),
  mnemonicLabel: () => cy.get(NewTransaction.mnemonicText),
  clientNameLabel: () => cy.get(NewTransaction.clientNameText),
  clientEmailLabel: () => cy.get(NewTransaction.clientEmailText),
  clientMobileNoLabel: () => cy.get(NewTransaction.clientMobileNoText),
  branchCodeLabel: () => cy.get(NewTransaction.branchCodeText),
  branchMnemonicLabel: () => cy.get(NewTransaction.branchMnemonicText),
  documentNameText: () => cy.get(NewTransaction.documentNameText),
  selectDocumentText: () => cy.get(NewTransaction.selectDocumentText),
  thresholdLabel: () => cy.get(NewTransaction.thresholdText),
  approverRuleLabel: () => cy.get(NewTransaction.approverRuleText),

  // Buttons
  previousPageButton: () => cy.get(NewTransaction.previousPageButton),
  sendButton: () => cy.get(NewTransaction.sendSubmit),
  clearButton: () => cy.get(NewTransaction.clearButton),
  productRadioButton: () => cy.get(NewTransaction.productRadio),
  documentRadioButton: () => cy.get(NewTransaction.documentRadio),
  uploadFileButton: () => cy.get(NewTransaction.uploadFileButton),
  previousYearSelectButton: () => cy.get(NewTransaction.previousYearSelectButton),
  nextYearSelectButton: () => cy.get(NewTransaction.nextYearSelectButton),

  // Input Box
  moseRefNoInput: () => cy.get(NewTransaction.moseRefNoInput),
  mnemonicInput: () => cy.get(NewTransaction.mnemonicInput),
  clientNameInput: () => cy.get(NewTransaction.clientNameInput),
  clientEmailInput: () => cy.get(NewTransaction.clientEmailInput),
  clientMobileNoInput: () => cy.get(NewTransaction.clientMobileNoInput),
  branchCodeInput: () => cy.get(NewTransaction.branchCodeInput),
  branchMnemonicInput: () => cy.get(NewTransaction.branchMnemonicInput),
  fileNameInput: () => cy.get(NewTransaction.fileNameInput),
  remarksInput: () => cy.get(NewTransaction.remarksInput),
  thresholdInput: () => cy.get(NewTransaction.thresholdInput),

  // Dropdown
  productTypeDropdown: () => cy.get(NewTransaction.productTypeDropdown),
  documentDropdown: () => cy.get(NewTransaction.documentDropdown),
  approverRuleDropdown: () => cy.get(NewTransaction.approverRuleDropdown),
  valueDateDropdown: () => cy.get(NewTransaction.valueDateDropdown),

  //Options
  assetSwapOption: () => cy.get(NewTransaction.assetSwapOption),
  creditDefaultSwapOption: () => cy.get(NewTransaction.creditDefaultSwapOption),
  crossCurrencySwapOption: () => cy.get(NewTransaction.crossCurrencySwapOption),
  depositPlusFxAgainstPhpOption: () => cy.get(NewTransaction.depositPlusFxAgainstPhpOption),
  depositPlusThirdCurrencyOption: () => cy.get(NewTransaction.depositPlusThirdCurrencyOption),
  derivativeTermsheetRdsOnlyOption: () => cy.get(NewTransaction.derivativeTermsheetRdsOnlyOption),
  derivativeWithOrderAtExpiryOption: () => cy.get(NewTransaction.derivativeWithOrderAtExpiryOption),
  fxForwardOption: () => cy.get(NewTransaction.fxForwardOption),
  fxOptionOption: () => cy.get(NewTransaction.fxOptionOption),
  fxSpotOption: () => cy.get(NewTransaction.fxSpotOption),
  fxSpotAndFixedIncomeOption: () => cy.get(NewTransaction.fxSpotAndFixedIncomeOption),
  fxSwapOption: () => cy.get(NewTransaction.fxSwapOption),
  fixedIncomeOption: () => cy.get(NewTransaction.fixedIncomeOption),
  interestRateSwapOption: () => cy.get(NewTransaction.interestRateSwapOption),
  leverageForInvestorsOption: () => cy.get(NewTransaction.leverageForInvestorsOption),
  mbChinaTimeDepositOption: () => cy.get(NewTransaction.mbChinaTimeDepositOption),
  nonDeliverableForwardOption: () => cy.get(NewTransaction.nonDeliverableForwardOption),
  nonDeliverableSwapOption: () => cy.get(NewTransaction.nonDeliverableSwapOption),
  structuredProductGpnBookBuildingOrderOption: () => cy.get(NewTransaction.structuredProductGpnBookBuildingOrderOption),
  structuredProductGlobalPesoNoteOption: () => cy.get(NewTransaction.structuredProductGlobalPesoNoteOption),
  structuredProductsOption: () => cy.get(NewTransaction.structuredProductsOption),
  treasuryTimeDepositOption: () => cy.get(NewTransaction.treasuryTimeDepositOption),
  unwideAssetSwapOption: () => cy.get(NewTransaction.unwindAssetSwapOption),
  unwindDepositPlusOption: () => cy.get(NewTransaction.unwindDepositPlusOption),
  unwindFixedIncomeAndStandaloneDerivativeOption: () => cy.get(NewTransaction.unwindFixedIncomeAndStandaloneDerivativeOption),
  unwindStructuredProductOption: () => cy.get(NewTransaction.unwindStructuredProductOption),
  datePickerPopperOption: () => cy.get(NewTransaction.datePickerPopperOption),
  suitabilityAssessmentFormLetterOfAppointmentOption: () => cy.get(NewTransaction.suitabilityAssessmentFormLetterOfAppointmentOption),

  //Table
  requiredDocumentsTable: () => cy.get(NewTransaction.requiredDocumentsTable),
  authorizedDealerCategoryATable: () => cy.get(NewTransaction.authorizedDealerCategoryATable),
  authorizedDealerCategoryBTable: () => cy.get(NewTransaction.authorizedDealerCategoryBTable),
  approverSetATable: () => cy.get(NewTransaction.approverSetATable),
  approverSetBTable: () => cy.get(NewTransaction.approverSetBTable),

  //Table Header
  requireddocumentsTableHeader: () => cy.get(NewTransaction.requiredDocumentsTableHeader),
  uploadFilesTableHeader: () => cy.get(NewTransaction.uploadFilesTableHeader),
  remarksTableHeader: () => cy.get(NewTransaction.remarksTableHeader),
  nameTableHeader: () => cy.get(NewTransaction.nameTableHeader),
  emailAddressTableHeader: () => cy.get(NewTransaction.emailAddressTableHeader),
  mobileNumberTableHeader: () => cy.get(NewTransaction.mobileNumberTableHeader),

  //Table Row
  requiredDocumentsTableRow: (id: number) => cy.get(`${NewTransaction.requiredDocumentsTableRow}${id}'`),
  authorizedDealerTableRow: (id: number) => cy.get(`${NewTransaction.authorizedDealerTableRow}${id}'`),
  approverSetATableRow: (id: number) => cy.get(`${NewTransaction.approverSetATableRow}${id}'`),
  approverSetBTableRow: (id: number) => cy.get(`${NewTransaction.approverSetBTableRow}${id}'`),
  approverSetTableRow: (id: number) => cy.get(`${NewTransaction.approverSetBTableRow}${id}'`),

  //Table Cell Data
  nameTableData: (id: number) => cy.get(`${NewTransaction.nameTableData}${id}'`),
  emailAddressTableData: (id: number) => cy.get(`${NewTransaction.emailAddressTableData}${id}'`),
  mobileNumberTableData: (id: number) => cy.get(`${NewTransaction.mobileNumberTableData}${id}'`),

  //+--------------------------------------------------------------------+
  //|                                                                    |
  //|                       ACTION METHODS                               |
  //|                                                                    |
  //+--------------------------------------------------------------------+

  typeMoseRefNoInput: (input: string) => cy.get(NewTransaction.moseRefNoInput).type(input),
  typeMnemonicInput: (input: string) => cy.get(NewTransaction.mnemonicInput).type(input),
  typeClientNameInput: (input: string) => cy.get(NewTransaction.clientNameInput).type(input),
  typeClientEmailInput: (input: string) => cy.get(NewTransaction.clientEmailInput).type(input),
  typeClientMobileNoInput: (input: string) => cy.get(NewTransaction.clientMobileNoInput).type(input),
  typeBranchCodeInput: (input: string) => cy.get(NewTransaction.branchCodeInput).type(input),
  typeBranchMnemonicInput: (input: string) => cy.get(NewTransaction.branchMnemonicInput).type(input),
  typeFileNameInput: (input: string) => cy.get(NewTransaction.fileNameInput).type(input),
  typeRemarksInput: (input: string) => cy.get(NewTransaction.remarksInput).type(input),
  typeThresholdInput: (input: string) => cy.get(NewTransaction.thresholdInput).type(input),

  clickProductTypeDropdown: () => cy.get(NewTransaction.productTypeDropdown).click(),
  clickDocumentDropdown: () => cy.get(NewTransaction.documentDropdown).click(),
  clickApproverRuleDropdown: () => cy.get(NewTransaction.approverRuleDropdown).click(),
  clickValueDateDropdown: () => cy.get(NewTransaction.valueDateDropdown).click(),

  clickPreviousPageButton: () => cy.get(NewTransaction.previousPageButton).click(),
  clickSendButton: () => cy.get(NewTransaction.sendSubmit).click(),
  clickClearButton: () => cy.get(NewTransaction.clearButton).click(),
  clickProductRadioButton: () => cy.get(NewTransaction.productRadio).click(),
  clickDocumentRadioButton: () => cy.get(NewTransaction.documentRadio).click(),
  clickUploadFileButton: () => cy.get(NewTransaction.uploadFileButton).click(),
  clickPreviousYearSelectButton: () => cy.get(NewTransaction.previousYearSelectButton).click(),
  clickNextYearSelectButton: () => cy.get(NewTransaction.nextYearSelectButton).click(),

  clickAssetSwapOption: () => cy.get(NewTransaction.assetSwapOption).click(),
  CreditDefaultSwapOption: () => cy.get(NewTransaction.creditDefaultSwapOption).click(),
  CrossCurrencySwapOption: () => cy.get(NewTransaction.crossCurrencySwapOption).click(),
  DepositPlusFxAgainstPhpOption: () => cy.get(NewTransaction.depositPlusFxAgainstPhpOption).click(),
  DepositPlusThirdCurrencyOption: () => cy.get(NewTransaction.depositPlusThirdCurrencyOption).click(),
  DerivativeTermsheetRdsOnlyOption: () => cy.get(NewTransaction.derivativeTermsheetRdsOnlyOption).click(),
  DerivativeWithOrderAtExpiryOption: () => cy.get(NewTransaction.derivativeWithOrderAtExpiryOption).click(),
  FxForwardOption: () => cy.get(NewTransaction.fxForwardOption).click(),
  FxOptionOption: () => cy.get(NewTransaction.fxOptionOption).click(),
  FxSpotOption: () => cy.get(NewTransaction.fxSpotOption).click(),
  FxSpotAndFixedIncomeOption: () => cy.get(NewTransaction.fxSpotAndFixedIncomeOption).click(),
  FxSwapOption: () => cy.get(NewTransaction.fxSwapOption).click(),
  FixedIncomeOption: () => cy.get(NewTransaction.fixedIncomeOption).click(),
  InterestRateSwapOption: () => cy.get(NewTransaction.interestRateSwapOption).click(),
  LeverageForInvestorsOption: () => cy.get(NewTransaction.leverageForInvestorsOption).click(),
  MbChinaTimeDepositOption: () => cy.get(NewTransaction.mbChinaTimeDepositOption).click(),
  NonDeliverableForwardOption: () => cy.get(NewTransaction.nonDeliverableForwardOption).click(),
  NonDeliverableSwapOption: () => cy.get(NewTransaction.nonDeliverableSwapOption).click(),
  StructuredProductGpnBookBuildingOrderOption: () => cy.get(NewTransaction.structuredProductGpnBookBuildingOrderOption).click(),
  StructuredProductGlobalPesoNoteOption: () => cy.get(NewTransaction.structuredProductGlobalPesoNoteOption).click(),
  StructuredProductsOption: () => cy.get(NewTransaction.structuredProductsOption).click(),
  TreasuryTimeDepositOption: () => cy.get(NewTransaction.treasuryTimeDepositOption).click(),
  UnwideAssetSwapOption: () => cy.get(NewTransaction.unwindAssetSwapOption).click(),
  UnwindDepositPlusOption: () => cy.get(NewTransaction.unwindDepositPlusOption).click(),
  UnwindFixedIncomeAndStandaloneDerivativeOption: () => cy.get(NewTransaction.unwindFixedIncomeAndStandaloneDerivativeOption).click(),
  UnwindStructuredProductOption: () => cy.get(NewTransaction.unwindStructuredProductOption).click(),
  UatePickerPopperOption: () => cy.get(NewTransaction.datePickerPopperOption).click(),
  SuitabilityAssessmentFormLetterOfAppointmentOption: () => cy.get(NewTransaction.suitabilityAssessmentFormLetterOfAppointmentOption).click(),

  clickRequiredDocumentsTableRow: (id: number) => cy.get(`${NewTransaction.requiredDocumentsTableRow}${id}'`).click(),
  clickAuthorizedDealerTableRow: (id: number) => cy.get(`${NewTransaction.authorizedDealerTableRow}${id}'`).click(),
  clickApproverSetATableRow: (id: number) => cy.get(`${NewTransaction.approverSetATableRow}${id}'`).click(),
  clickApproverSetBTableRow: (id: number) => cy.get(`${NewTransaction.approverSetBTableRow}${id}'`).click(),
  clickApproverSetTableRow: (id: number) => cy.get(`${NewTransaction.approverSetBTableRow}${id}'`).click(),
}
