import { TCViewProcessing } from '../../../locators/viewProcessing'
export const TCViewProcessingPage = {
  filterByDropdown: () => cy.get(TCViewProcessing.filterByDropdown),
  clientTypeDropdown: () => cy.get(TCViewProcessing.clientTypeDropdown),
  searchBarInput: () => cy.get(TCViewProcessing.searchBarInput),
  clientNameOptions: () => cy.get(TCViewProcessing.clientNameOptions),
  clientMnemonicOptions: () => cy.get(TCViewProcessing.clientMnemonicOptions),
  moseRefNoOptions: () => cy.get(TCViewProcessing.moseRefNoOptions),
  productOptions: () => cy.get(TCViewProcessing.productOptions),
  statusOptions: () => cy.get(TCViewProcessing.statusOptions),
  branchCodeOptions: () => cy.get(TCViewProcessing.branchCodeOptions),
  branchMnemonicOptions: () => cy.get(TCViewProcessing.branchMnemonicOptions),
  originatorOptions: () => cy.get(TCViewProcessing.originatorOptions),
  allOptions: () => cy.get(TCViewProcessing.allOptions),
  retailOptions: () => cy.get(TCViewProcessing.retailOptions),
  corporateOptions: () => cy.get(TCViewProcessing.corporateOptions),
  viewTransactionTable: () => cy.get(TCViewProcessing.viewTransactionTable),
  clientMnemonicTableHeader: () => cy.get(TCViewProcessing.clientMnemonicTableHeader),
  clientNameTableHeader: () => cy.get(TCViewProcessing.clientNameTableHeader),
  moseRefNoTableHeader: () => cy.get(TCViewProcessing.moseRefNoTableHeader),
  branchCodeTableHeader: () => cy.get(TCViewProcessing.branchCodeTableHeader),
  branchMnemonicTableHeader: () => cy.get(TCViewProcessing.branchMnemonicTableHeader),
  servicingUnitTableHeader: () => cy.get(TCViewProcessing.servicingUnitTableHeader),
  productTableHeader: () => cy.get(TCViewProcessing.productTableHeader),
  statusTableHeader: () => cy.get(TCViewProcessing.statusTableHeader),
  transactionDateTableHeader: () => cy.get(TCViewProcessing.transactionDateTableHeader),
  originatorTableHeader: () => cy.get(TCViewProcessing.originatorTableHeader),
  valueDateTableHeader: () => cy.get(TCViewProcessing.valueDateTableHeader),
  clientTypeTableHeader: () => cy.get(TCViewProcessing.clientTypeTableHeader),
  retailClientTypeTableHeader: () => cy.get(TCViewProcessing.retailClientTypeTableHeader),
  viewTransactionTableRow: (index: number) => cy.get(`${TCViewProcessing.viewTransactionTableRow}${index}`),
  clientMnemonicTableData: (index: number) => cy.get(`${TCViewProcessing.clientMnemonicTableData}${index}`),
  clientNameTableData: (index: number) => cy.get(`${TCViewProcessing.clientNameTableData}${index}`),
  moseRefNoTableData: (index: number) => cy.get(`${TCViewProcessing.moseRefNoTableData}${index}`),
  branchCodeTableData: (index: number) => cy.get(`${TCViewProcessing.branchCodeTableData}${index}`),
  branchMnemonicTableData: (index: number) => cy.get(`${TCViewProcessing.branchMnemonicTableData}${index}`),
  servicingUnitTableData: (index: number) => cy.get(`${TCViewProcessing.servicingUnitTableData}${index}`),
  productTableData: (index: number) => cy.get(`${TCViewProcessing.productTableData}${index}`),
  statusTableData: (index: number) => cy.get(`${TCViewProcessing.statusTableData}${index}`),
  transactionDateTableData: (index: number) => cy.get(`${TCViewProcessing.transactionDateTableData}${index}`),
  originatorTableData: (index: number) => cy.get(`${TCViewProcessing.originatorTableData}${index}`),
  valueDateTableData: (index: number) => cy.get(`${TCViewProcessing.valueDateTableData}${index}`),
  clientTypeTableData: (index: number) => cy.get(`${TCViewProcessing.clientTypeTableData}${index}`),
  retailClientTypeTableData: (index: number) => cy.get(`${TCViewProcessing.retailClientTypeTableData}${index}`),
  selectAllButton: () => cy.get(TCViewProcessing.selectAllButton),
  selectTransactionInput: (index: number) => cy.get(`${TCViewProcessing.selectTransactionInput}${index}`),
  rowsPerPageText: () => cy.get(TCViewProcessing.rowsPerPageText),
  rowsPerPageDropdown: () => cy.get(TCViewProcessing.rowsPerPageDropdown),
  previousPageButton: () => cy.get(TCViewProcessing.previousPageButton),
  nextPageButton: () => cy.get(TCViewProcessing.nextPageButton),
  pageCountText: () => cy.get(TCViewProcessing.pageCountText),
  
  //+--------------------------------------------------------------------+
  //|                                                                    |
  //|                       ACTION METHODS                               |
  //|                                                                    |
  //+--------------------------------------------------------------------+

  clickFilterByDropdown: () => cy.get(TCViewProcessing.filterByDropdown).click,
  clickClientTypeDropdown: () => cy.get(TCViewProcessing.clientTypeDropdown).click,
  clickSearchBarInput: () => cy.get(TCViewProcessing.searchBarInput).click,
  clickClientNameOptions: () => cy.get(TCViewProcessing.clientNameOptions).click,
  clickClientMnemonicOptions: () => cy.get(TCViewProcessing.clientMnemonicOptions).click,
  clickMoseRefNoOptions: () => cy.get(TCViewProcessing.moseRefNoOptions).click,
  clickProductOptions: () => cy.get(TCViewProcessing.productOptions).click,
  clickStatusOptions: () => cy.get(TCViewProcessing.statusOptions).click,
  clickBranchCodeOptions: () => cy.get(TCViewProcessing.branchCodeOptions).click,
  clickBranchMnemonicOptions: () => cy.get(TCViewProcessing.branchMnemonicOptions).click,
  clickOriginatorOptions: () => cy.get(TCViewProcessing.originatorOptions).click,
  clickAllOptions: () => cy.get(TCViewProcessing.allOptions).click,
  clickRetailOptions: () => cy.get(TCViewProcessing.retailOptions).click,
  clickCorporateOptions: () => cy.get(TCViewProcessing.corporateOptions).click,
  clickSelectAllButton: () => cy.get(TCViewProcessing.selectAllButton).click,
  clickRowsPerPageDropdown: () => cy.get(TCViewProcessing.rowsPerPageDropdown).click,
  clickPreviousPageButton: () => cy.get(TCViewProcessing.previousPageButton).click,
  clickNextPageButton: () => cy.get(TCViewProcessing.nextPageButton).click,
}
